### PR TITLE
Added official fedora repository

### PR DESCRIPTION
**Pull request by jatin-cbs**
- Added Fedora icon
- Added link to Fedora Cadence rpm src

### CODE REVIEW

**Comment by jatin-cbs** [comment]
@falkTX  :+1:  do consider this pull request.

**Comment by jatin-cbs** [comment]
Closing as this is not considered.

**Comment by falkTX** [comment]
Please dont close this. I just was doing something else, and am not in any way experienced on Fedora stuff.
It also requires more thinking than just adding distro icons, otherwise adding a badge for every distro would make the OS list quite big.

**Comment by jatin-cbs** [comment]
Oh ok will reopen this I will re create the fork

**Pull request closed without merging**
